#!/usr/bin/python
# coding: utf-8
import logging
from sys import argv
import urllib2
import tempfile
from os.path import exists
import imp
from json import loads as jsondecode

log = logging.getLogger("ses")
# repos has to start with http:// or https://
repos = [
    "http://localhost:6005/",
    "https://sundayzone.com/ses/",
    "http://sundayzone.com/ses/"
]


def debug():
    return False


if debug():
    logging.basicConfig()
    log.setLevel(logging.DEBUG)
else:
    logging.basicConfig()
    log.setLevel(logging.INFO)


# The only reason why implementing this instead of using python-request
# - or other fancy http libs - is to avoid any external libraries, so
# that it can easily be installed.
def httpdownload(url):
    try:
        # Apparently cloudflare blocks anything that does not have a user agent.
        headers = {
            #'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11'
            'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
        }
        req = urllib2.Request(url, headers=headers)
        response = urllib2.urlopen(url)
        if response.getcode() != 200:
            return None
        return response.read()
    except Exception as e:
        log.debug("'{}' not found. Exception {}".format(url, e))
        return None
    # TODO: Figure out what exactly urlopen can give of exceptions,
    # and print out better error messages.


def getarg(i):
    try:
        return argv[i]
    except:
        return None


def getrestofargs(i):
    try:
        return argv[i:]
    except:
        return []


def betterexec(snippet):
    """ This takes a snippet string and import it as a file """
    snippetfile = tempfile.NamedTemporaryFile()
    snippetfile.write(snippet)
    snippetfile.flush()
    obj = imp.load_source("name", snippetfile.name)
    snippetfile.close()
    return obj


def getsnippet(torun):
    for repo in repos:
        if not repo.endswith("/"):
            repo += "/"
        
        print("Trying to fetch '{}'".format(repo + torun))
        snippet = httpdownload(repo + torun)

        if snippet is None:
            log.debug("Snippet not found.")
        else:
            print("FOUND  {} snippet!".format(torun))
            return snippet

    return None


def run(snippetname, snippetargs):
    snippet = getsnippet(snippetname)
    if snippet is None:
        print("Could not find snippet.")
        return

    print("Running snippet..")
    betterexec(snippet).main(snippetargs)


def info(snippetname):
    snippet = getsnippet(snippetname)
    if snippet is None:
        print("Could not find snippet.")
        return

    print(betterexec(snippet).__doc__)


def listsnippets():
    totalindex = []

    # Getting them
    for repo in repos:
        index = httpdownload(repo + "index")
        if index is None:
            continue
        index = jsondecode(index)

        # Adding to totalindex, unles already there.
        for snippet in index:
            if not snippet in totalindex:
                totalindex.append(snippet)

    # Showing them
    for snippet in totalindex:
        print("{name} - {description}".format(**snippet))


def downloadsnippet(snippetname):
    if exists(snippetname + ".py"):
        print("File '{}' already exists. Please remove or move the file before downloading snippet.".
                format(snippetname + ".py"))
        return

    snippet = getsnippet(snippetname)
    if snippet is None:
        print("Could not find snippet")
        return

    print("Now writing it to '{}.py'".format(snippetname))
    with open(snippetname + ".py", "w") as f:
        f.write(snippet)


def main():
    cmd = getarg(1)
    if cmd == "run":
        run(getarg(2), getrestofargs(3))

    elif cmd == "info":
        info(getarg(2))

    elif cmd == "list":
        listsnippets()

    elif cmd == "pull":
        downloadsnippet(getarg(2))

    else:
        print("""usage: ses <command> [<args>]

Supprted commands are:
   run      Run a snippet by the name of args[0] with the arguments args[1:]
   list     List all available snippets from your repositories.
   info     Finds information about the snippet named args[0].
   pull     Get the snippet and save it as <snippetname>.py
   help     Shows this text

Examples:
  To create a new Go project named MyAwesomeProject, you can type:
     ses run bootstrapgo MyAwesomeProject
 
  If you want to find all snippets named bootstrap you can do
     ses list | grep bootstrap

  Update ses can be done by
     ses run update
  since there is a snippet called update.

See more at https://github.com/Smarties89/ses""")


if __name__ == "__main__":
    main()
