#!/bin/python
# coding: utf-8

"""
    Updates ses to newest version. Executes the same commands as
    https://github.com/Smarties89/ses section "How does ses work"
"""

__author__ = "smarties89 at github"


from subprocess import call


def main(args):
    cmds = """
# This is for removing the old installation way.
sudo rm /usr/bin/ses
# Fetch and give it execution right
# TODO: Check if one the commands exist and then only use that one.
sudo wget https://raw.githubusercontent.com/Smarties89/ses/master/ses --output-document=/usr/local/bin/ses
sudo curl "https://raw.githubusercontent.com/Smarties89/ses/master/ses" -o "/usr/local/bin/ses"
sudo chmod +x /usr/local/bin/ses
"""
    call(cmds, shell=True)


if __name__ == "__main__":
    main([])
